# Generated by Django 5.1.1 on 2024-10-09 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'start_time'], 'verbose_name': 'Đơn đặt sân', 'verbose_name_plural': 'Đơn đặt sân'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Lịch sử thanh toán', 'verbose_name_plural': 'Lịch sử thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name': 'Sân bóng', 'verbose_name_plural': 'Sân bóng'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Đã đặt'), ('canceled', 'Đã hủy'), ('paid', 'Đã thanh toán')], default='booked', max_length=8, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên sân'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá mỗi giờ'),
        ),
    ]
