# Generated by Django 5.1.1 on 2024-10-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Địa chỉ', 'verbose_name_plural': 'Địa chỉ'},
        ),
    ]
